version: '3.9'

services:

  php:
    container_name: php
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/ini:/usr/local/etc/php/custom.d
#    environment:
#      # Необходимы для xDebug
#      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
#      PHP_IDE_CONFIG: 'serverName=Docker'
#    extra_hosts:
#      # Необходим для xDebug на UNIX системах
#      - host.docker.internal:host-gateway

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '8777:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  postgres:
    container_name: postgres
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    depends_on:
      - php

  rabbit:
    container_name: rabbit
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - '15672:15672'
      - '5672:5672'